# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/ublue-broadcom-wl
name: ublue-broadcom-wl
description: Bazzite DX with Broadcom drivers and iwd backend

# The base image to build on top of
base-image: ghcr.io/ublue-os/bazzite-dx
image-version: latest 

modules:
  # Copies any custom files into the OS
  - type: files
    files:
      - source: system
        destination: / 

  # Installs the Broadcom drivers from RPM Fusion (already enabled in Bazzite)
  - type: rpm-ostree
    install:
      - broadcom-wl
      - akmod-wl

  # Sets up the proper policy & signing files for signed images to work securely
  - type: signing
